Repository CoinShift-Imaging/CoinShift-Imaging-Box, pull requests merged in 2021-03, with the labels that each got.

#52 Update README.md
  README.md
Labels: Level0, gssoc21

#58 Fillin in masked words with RoBERTa
  NLP/filling-in-masked-words-with-roberta.ipynb
Labels: Level3, gssoc21

#57 Added Imagenet classification Folder
  Classification_Zoo/Imagenet classification/DataSet/Link.txt
  Classification_Zoo/Imagenet classification/Dog.png
  Classification_Zoo/Imagenet classification/Image_Classifier.ipynb
  Classification_Zoo/Imagenet classification/README.md
  Classification_Zoo/Imagenet classification/app.py
  Classification_Zoo/Imagenet classification/images/1.jpg
  Classification_Zoo/Imagenet classification/images/589c80e564b351149f22a81f.png
  Classification_Zoo/Imagenet classification/images/turtle_PNG69.png
  Classification_Zoo/Imagenet classification/static/css/main.css
  Classification_Zoo/Imagenet classification/static/js/main.js
  Classification_Zoo/Imagenet classification/templates/base.html
  Classification_Zoo/Imagenet classification/templates/index.html
  Classification_Zoo/Imagenet classification/uploads/Screenshot (268).png
Labels: Level2, gssoc21
